default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --target lib/main.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:409966899479:android:89b1480be41f5958534752",
      firebase_cli_token: ُENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "ma5275780@gmail.com",
      release_notes: "First Fastlane Firebase Distribution YouTube Video!"
    )
  end
end
